/* =============================================================================
   ODL Interactive Process Guide — estimation engine + content data
   -----------------------------------------------------------------------------
   PROVENANCE OF NUMBERS (so every figure is defensible to faculty / the Director):
   - CALIBRATION block below is machine-generated by ../inject_calibration.py
     from data_all/derived/calibration.json — itself computed by ../calibrate.py
     from 2,335 real Asana time entries (2,053 h, 2024-08 → 2026-06, 55 projects;
     calibration set = 25 fully-tracked course-dev projects). Do NOT edit the
     block by hand; re-run the pipeline after each new Asana pull.
   - Media/graphics per-deliverable HOURS come from ODL's own "ODL Project
     Estimations" Asana board (Nov 2024), incl. Pre/Prod/Post splits. Logged
     data validates the lecture-band rates: observed full-lifecycle short-video
     median 12.8 h/video (n=5), shrinkage-blended generic rate 11.2 h/video.
     Interview/testimonial/mini-doc rates remain UNVALIDATED (no fully-logged
     exemplar yet).
   - PM hours are CALIBRATED: hours-per-calendar-week quartiles from the 14
     PM-tracked projects (replaces the old size-bucket extrapolation).
   - Calendar: per-archetype span quartiles from completed_at timestamps with
     bulk check-off filtering (full courses: median 31 wk, IQR 18–42, n=23).
   - Impact Tracker status is pulled from the Asana project custom field
     "Impact Tracker Status" and summarized as a performance/compliance signal.
   - Impact Tracker task fields, when exported to task_custom_fields.csv, are
     used as an asset-count cross-check only after matching to fully tracked
     projects produces a defensible hours-per-asset calibration.
   - FACULTY-time figures are ODL learning-design & media leads' own planning
     estimates (2026): media 1h pre + 1h prod + 0.5h post per video; design goals
     2-4h (fixed) and a course map that scales with course size (~6-30h); 3-10h per module for build/QA; and
     ~1h per calendar week for working meetings. No faculty time is logged yet, so
     these stay planning estimates (labeled as such) and are shown as ranges.
   - Design / Discovery / QA / Evaluation ODL-side hours remain planning estimates
     (logged data has <15 h each of Discovery/QA/Evaluation — see not_calibratable).
   Architecture: this file computes ALL numbers deterministically. No AI/LLM
   number generation. Estimates are ranges, never false-precision points.
   ============================================================================= */
(function (root) {
  "use strict";

  // === BEGIN CALIBRATION (machine-generated — do not edit by hand) ==========
  var CALIBRATION =
  {
    "provenance": "data_all/time_entries.csv (3,331 entries, 2838.3h, 2024-07-10..2026-07-15, ODL staff time) | 25 full-coverage course-dev projects >=10h (derived/ground_truth.csv); production rates from the 21 of them with >=10h non-PM logging",
    "generated_from": "data_all/derived/calibration.json -- run inject_calibration.py to refresh",
    "archetypeEffort": {
      "course_redesign": {
        "n": 2,
        "values": [
          32.3,
          33.4
        ],
        "p50": 32.8,
        "note": "n<4 -- raw values shown; interpolated quartiles withheld"
      },
      "full_course": {
        "n": 14,
        "min": 15.7,
        "p25": 29.2,
        "p50": 47.2,
        "p75": 77.9,
        "p80": 87.7,
        "max": 286.5
      },
      "single_video": {
        "n": 3,
        "values": [
          12.0,
          15.5,
          29.8
        ],
        "p50": 15.5,
        "note": "n<4 -- raw values shown; interpolated quartiles withheld"
      },
      "video_series": {
        "n": 2,
        "values": [
          29.2,
          54.8
        ],
        "p50": 42.0,
        "note": "n<4 -- raw values shown; interpolated quartiles withheld"
      }
    },
    "pmPerWeek": {
      "n": 14,
      "min": 0.3,
      "p25": 0.6,
      "p50": 0.8,
      "p75": 1.6,
      "p80": 2.0,
      "max": 3.9
    },
    "pmSharePctWhereBothLogged": {
      "n": 7,
      "min": 13.7,
      "p25": 16.0,
      "p50": 36.1,
      "p75": 51.0,
      "p80": 59.1,
      "max": 73.3
    },
    "videoRate": {
      "observed": {
        "n": 5,
        "min": 7.3,
        "p25": 12.0,
        "p50": 13.7,
        "p75": 15.5,
        "p80": 18.4,
        "max": 29.8
      },
      "blendedGenericP50": 11.8,
      "shrinkageW": 0.62
    },
    "mediaSplitPct": {
      "Post-Production": 41.9,
      "Pre-Production": 25.8,
      "Production": 32.3
    },
    "mediaSplitBasis": "pooled hours on per-video sections with full-coverage logging: 1 project(s) (Program for Inclusive Education (PIE) Video #2), 15.5h total",
    "coursePhaseMixPct": {
      "Production": 34.2,
      "Post-Production": 23.6,
      "Development/Build": 16.4,
      "Pre-Production": 16.2,
      "Design": 7.9,
      "Other / unsorted": 1.3,
      "Discovery": 0.4
    },
    "coursePhaseMixBasis": "pooled non-PM hours of 14 full-coverage full_course projects (952.3h)",
    "calendarWeeks": {
      "consult_or_studio": {
        "n": 1,
        "values": [
          44.0
        ]
      },
      "course_redesign": {
        "n": 3,
        "values": [
          7.8,
          10.3,
          23.3
        ],
        "p50": 10.3,
        "note": "n<4 -- raw values shown; interpolated quartiles withheld"
      },
      "full_course": {
        "n": 23,
        "min": 4.8,
        "p25": 17.7,
        "p50": 31.4,
        "p75": 41.9,
        "p80": 46.6,
        "max": 63.6
      },
      "podcast": {
        "n": 2,
        "values": [
          6.5,
          84.6
        ],
        "p50": 45.5,
        "note": "n<4 -- raw values shown; interpolated quartiles withheld"
      },
      "single_video": {
        "n": 4,
        "min": 2.0,
        "p25": 2.4,
        "p50": 3.9,
        "p75": 7.2,
        "p80": 8.4,
        "max": 13.0
      },
      "sprint": {
        "n": 1,
        "values": [
          13.9
        ]
      },
      "video_series": {
        "n": 4,
        "min": 5.4,
        "p25": 9.6,
        "p50": 12.1,
        "p75": 14.3,
        "p80": 14.9,
        "max": 17.4
      },
      "xr_interactive": {
        "n": 4,
        "min": 10.0,
        "p25": 10.8,
        "p50": 16.0,
        "p75": 22.0,
        "p80": 22.7,
        "max": 25.3
      }
    },
    "impactTracker": {
      "field": "cf::Impact Tracker Status",
      "basis": "data_all/projects.csv Asana project custom field across 223 pulled projects",
      "total_projects": 223,
      "tracked_projects": 33,
      "blank_projects": 190,
      "coverage_pct": 14.8,
      "status_counts": {
        "Up to date": 21,
        "Outdated": 12
      },
      "up_to_date_pct_of_tracked": 63.6,
      "outdated_projects": [
        {
          "project_gid": "1207760971753716",
          "project": "FCTA - Physics I",
          "status": "Outdated"
        },
        {
          "project_gid": "1207942229848224",
          "project": "National Education Opportunities Network (NEON)",
          "status": "Outdated"
        },
        {
          "project_gid": "1209298164735103",
          "project": "AI for the Notre Dame Community",
          "status": "Outdated"
        },
        {
          "project_gid": "1209417474929053",
          "project": "Business on the Frontlines XR",
          "status": "Outdated"
        },
        {
          "project_gid": "1209679644127773",
          "project": "Radio Systems Course",
          "status": "Outdated"
        },
        {
          "project_gid": "1211900372320318",
          "project": "C2D: Cybertraining for Chemical Data scientists",
          "status": "Outdated"
        },
        {
          "project_gid": "1212660352662527",
          "project": "Romance Languages video/podcast initiative",
          "status": "Outdated"
        },
        {
          "project_gid": "1213393701257435",
          "project": "Digital Accessibility",
          "status": "Outdated"
        },
        {
          "project_gid": "1213551317973102",
          "project": "ODL Media Studio Sessions",
          "status": "Outdated"
        },
        {
          "project_gid": "1214783923511446",
          "project": "Sprint - Unlocking Inaccessible Korean Heritage",
          "status": "Outdated"
        },
        {
          "project_gid": "1214795652576790",
          "project": "Maximizing Mendoza",
          "status": "Outdated"
        },
        {
          "project_gid": "1215646180453827",
          "project": "CAD 2026 - Stephen Blackburn Videos",
          "status": "Outdated"
        }
      ]
    },
    "impactCustomFields": {
      "available": true,
      "source": "data_all/task_custom_fields.csv",
      "metric_scope": "Impact Tracker board tasks only",
      "value_count": 5472,
      "field_count": 38,
      "all_fields": [
        "Academic Department",
        "Additional Comments",
        "Canvas Courses",
        "Credit-Bearing",
        "End Date",
        "Faculty Collaborators",
        "Faculty Satisfaction Index",
        "Fees",
        "Google Drive Folder Title",
        "Graphics",
        "Handoff Document",
        "IP Agreement",
        "Interactives",
        "Link to Handoff Document",
        "Link to IP Agreement",
        "Link to MOU",
        "Link to Project Charter",
        "Link to Reflection Report",
        "MOU",
        "Net Promoter Score",
        "ODL Departments Involved",
        "Post-Project Evaluation",
        "Project Charter",
        "Project Type",
        "Start Date",
        "Status",
        "Student Reach / Year",
        "Summary",
        "T-Shirt Size",
        "Team Members",
        "Total Assets",
        "Total Hours",
        "Total Hours (2024)",
        "Total Hours (2025)",
        "Total Hours (2026)",
        "Videos",
        "Web Page Modules",
        "XR experiences"
      ],
      "record_count": 144,
      "detected_asset_fields": [
        "Canvas Courses",
        "Graphics",
        "Interactives",
        "Total Assets",
        "Videos",
        "Web Page Modules",
        "XR experiences"
      ],
      "detected_satisfaction_fields": [
        "Faculty Satisfaction Index"
      ],
      "asset_field_stats": {
        "Canvas Courses": {
          "n": 28,
          "min": 0.0,
          "p25": 0.0,
          "p50": 1.0,
          "p75": 1.0,
          "p80": 1.0,
          "max": 2.0
        },
        "Graphics": {
          "n": 28,
          "min": 0.0,
          "p25": 0.0,
          "p50": 0.0,
          "p75": 0.0,
          "p80": 0.0,
          "max": 8.0
        },
        "Interactives": {
          "n": 27,
          "min": 0.0,
          "p25": 0.0,
          "p50": 0.0,
          "p75": 0.0,
          "p80": 0.0,
          "max": 1.0
        },
        "Total Assets": {
          "n": 144,
          "min": 0.0,
          "p25": 0.0,
          "p50": 0.0,
          "p75": 0.0,
          "p80": 1.0,
          "max": 114.0
        },
        "Videos": {
          "n": 29,
          "min": 0.0,
          "p25": 0.0,
          "p50": 0.0,
          "p75": 14.0,
          "p80": 17.4,
          "max": 114.0
        },
        "Web Page Modules": {
          "n": 26,
          "min": 0.0,
          "p25": 0.0,
          "p50": 0.0,
          "p75": 0.0,
          "p80": 0.0,
          "max": 4.0
        },
        "XR experiences": {
          "n": 28,
          "min": 0.0,
          "p25": 0.0,
          "p50": 0.0,
          "p75": 0.0,
          "p80": 0.6,
          "max": 1.0
        }
      },
      "satisfaction_field_stats": {
        "Faculty Satisfaction Index": {
          "n": 24,
          "min": 4.4,
          "p25": 4.7,
          "p50": 4.9,
          "p75": 5.0,
          "p80": 5.0,
          "max": 5.0
        }
      },
      "records_with_assets": 31,
      "records_with_satisfaction": 24,
      "matched_records": 50,
      "outcomes": {
        "faculty_satisfaction_index": {
          "n": 24,
          "min": 4.4,
          "p25": 4.7,
          "p50": 4.9,
          "p75": 5.0,
          "p80": 5.0,
          "max": 5.0,
          "mean": 4.84
        },
        "net_promoter_score": {
          "n": 24,
          "min": 90.0,
          "p25": 100.0,
          "p50": 100.0,
          "p75": 100.0,
          "p80": 100.0,
          "max": 100.0,
          "mean": 99.38
        },
        "student_reach_per_year": null
      },
      "compliance": {
        "Handoff Document": {
          "counts": {
            "No": 88,
            "Yes": 24
          },
          "answered": 112,
          "applicable": 112,
          "yes": 24,
          "yes_pct_of_applicable": 21.4
        },
        "IP Agreement": {
          "counts": {
            "No": 91,
            "Yes": 20,
            "Not Signed": 9,
            "N/A": 3,
            "In Progress": 1
          },
          "answered": 124,
          "applicable": 121,
          "yes": 20,
          "yes_pct_of_applicable": 16.5
        },
        "MOU": {
          "counts": {
            "Yes": 7,
            "N/A": 5,
            "In Progress": 2
          },
          "answered": 14,
          "applicable": 9,
          "yes": 7,
          "yes_pct_of_applicable": 77.8
        },
        "Post-Project Evaluation": {
          "counts": {
            "Yes": 22,
            "No": 9
          },
          "answered": 31,
          "applicable": 31,
          "yes": 22,
          "yes_pct_of_applicable": 71.0
        },
        "Project Charter": {
          "counts": {
            "No": 59,
            "Yes": 34,
            "Not Signed": 15,
            "In Progress": 14,
            "Other Plan": 5,
            "Addendum": 1
          },
          "answered": 128,
          "applicable": 128,
          "yes": 34,
          "yes_pct_of_applicable": 26.6
        }
      },
      "tracker_status_counts": {
        "Complete": 74,
        "In Progress": 28,
        "No Documentation": 15,
        "On Hold": 4
      },
      "assets_produced_total": 358.0,
      "asset_field_totals": {
        "Canvas Courses": 21.0,
        "Graphics": 15.0,
        "Interactives": 3.0,
        "Total Assets": 358.0,
        "Videos": 309.0,
        "Web Page Modules": 4.0,
        "XR experiences": 6.0
      },
      "reported_hours_by_year": {
        "2025": 5815.0
      },
      "hours_crosscheck": {
        "n": 18,
        "median_ratio_logged_over_reported": 0.38,
        "rows": [
          {
            "project": "3D Environments Summer Online",
            "project_gid": "1208878713359040",
            "tracker_reported_hours": 72.0,
            "asana_logged_hours": 35.2,
            "ratio_logged_over_reported": 0.49
          },
          {
            "project": "ACE Assessment Course Redesign",
            "project_gid": "1208622917750063",
            "tracker_reported_hours": 84.5,
            "asana_logged_hours": 33.4,
            "ratio_logged_over_reported": 0.4
          },
          {
            "project": "ACE Higher Powered Learning (HPL)",
            "project_gid": "1211134268245785",
            "tracker_reported_hours": 523.0,
            "asana_logged_hours": 26.0,
            "ratio_logged_over_reported": 0.05
          },
          {
            "project": "ASCEND Engineering",
            "project_gid": "1209213189516073",
            "tracker_reported_hours": 159.0,
            "asana_logged_hours": 102.9,
            "ratio_logged_over_reported": 0.65
          },
          {
            "project": "ASCEND MCOB",
            "project_gid": "1212343204566399",
            "tracker_reported_hours": 8.0,
            "asana_logged_hours": 93.0,
            "ratio_logged_over_reported": 11.62
          },
          {
            "project": "Business for Humans | Sheedy Family Program",
            "project_gid": "1211653962736510",
            "tracker_reported_hours": 12.0,
            "asana_logged_hours": 47.8,
            "ratio_logged_over_reported": 3.98
          },
          {
            "project": "C2D: Cybertraining for Chemical Data scientists",
            "project_gid": "1211900372320318",
            "tracker_reported_hours": 20.0,
            "asana_logged_hours": 16.5,
            "ratio_logged_over_reported": 0.82
          },
          {
            "project": "CIF Video",
            "project_gid": "1212638028070139",
            "tracker_reported_hours": 29.0,
            "asana_logged_hours": 9.0,
            "ratio_logged_over_reported": 0.31
          },
          {
            "project": "FCTA - Calculus I",
            "project_gid": "1208031566113859",
            "tracker_reported_hours": 43.0,
            "asana_logged_hours": 2.8,
            "ratio_logged_over_reported": 0.07
          },
          {
            "project": "FCTA - Physics I",
            "project_gid": "1207760971753716",
            "tracker_reported_hours": 127.0,
            "asana_logged_hours": 41.9,
            "ratio_logged_over_reported": 0.33
          },
          {
            "project": "Force for Good Video Project",
            "project_gid": "1211154824956969",
            "tracker_reported_hours": 105.5,
            "asana_logged_hours": 45.1,
            "ratio_logged_over_reported": 0.43
          },
          {
            "project": "I CAN HELP Learning Modules",
            "project_gid": "1211900373500710",
            "tracker_reported_hours": 17.0,
            "asana_logged_hours": 6.0,
            "ratio_logged_over_reported": 0.35
          },
          {
            "project": "MS-ACMS Faculty Videos",
            "project_gid": "1211489930659695",
            "tracker_reported_hours": 33.0,
            "asana_logged_hours": 5.0,
            "ratio_logged_over_reported": 0.15
          },
          {
            "project": "MSAN",
            "project_gid": "1208014741125322",
            "tracker_reported_hours": 71.0,
            "asana_logged_hours": 8.0,
            "ratio_logged_over_reported": 0.11
          },
          {
            "project": "MSAN II",
            "project_gid": "1208335647365608",
            "tracker_reported_hours": 50.0,
            "asana_logged_hours": 71.1,
            "ratio_logged_over_reported": 1.42
          },
          {
            "project": "ODL Lookbook",
            "project_gid": "1208659811898324",
            "tracker_reported_hours": 75.0,
            "asana_logged_hours": 22.3,
            "ratio_logged_over_reported": 0.3
          },
          {
            "project": "Responsible and Ethical AI",
            "project_gid": "1208963580488220",
            "tracker_reported_hours": 918.0,
            "asana_logged_hours": 278.6,
            "ratio_logged_over_reported": 0.3
          },
          {
            "project": "Veterans College Math Readiness Course",
            "project_gid": "1211385006360353",
            "tracker_reported_hours": 66.0,
            "asana_logged_hours": 108.8,
            "ratio_logged_over_reported": 1.65
          }
        ],
        "basis": "Tracker 'Total Hours' field vs hours actually logged in Asana time entries for the same project (matched by GID or unique normalized name)."
      },
      "asset_hours_per_asset": {
        "usable_for_estimation": true,
        "hours_per_asset": {
          "n": 4,
          "min": 0.9,
          "p25": 2.0,
          "p50": 2.5,
          "p75": 5.9,
          "p80": 7.9,
          "max": 15.8
        },
        "matched_full_coverage_projects": [
          {
            "project": "MSAN II",
            "project_gid": "1208335647365608",
            "asset_total": 27.0,
            "non_pm_hours": 71.1,
            "hours_per_asset": 2.63
          },
          {
            "project": "Responsible and Ethical AI",
            "project_gid": "1208963580488220",
            "asset_total": 114.0,
            "non_pm_hours": 98.9,
            "hours_per_asset": 0.87
          },
          {
            "project": "ACE Assessment Course Redesign",
            "project_gid": "1208622917750063",
            "asset_total": 14.0,
            "non_pm_hours": 33.4,
            "hours_per_asset": 2.39
          },
          {
            "project": "Travel Safety 101",
            "project_gid": "1208255134985069",
            "asset_total": 1.0,
            "non_pm_hours": 15.7,
            "hours_per_asset": 15.75
          }
        ],
        "basis": "Impact Tracker asset-count fields joined to full-coverage Asana time entries by project GID or normalized project/task name.",
        "note": null
      }
    },
    "notCalibratable": {
      "faculty_time": "time_entries contains ODL STAFF time only -- zero faculty hours logged. All faculty-time figures remain planning estimates and must be labeled as such.",
      "discovery_effort": "only 19.1h logged across all projects -- discovery happens before boards get tracked. Insufficient.",
      "evaluation_effort": "only 29.3h logged total. Insufficient.",
      "qa_effort": "only 1.7h logged total. Insufficient.",
      "interview_minidoc_video_rates": "no full-coverage logged exemplar (see video block).",
      "xr_effort": "XR projects in data have <=6h logged (Equity XR 6h, XR Spanish 1h) -- board rates (40-80h) stand, unvalidated.",
      "per_module_rate": "module counts exist for only 5 of 19 course projects and mean different things (AI for ND 57h/module vs R&E AI 7.6h/week-unit vs Virtual Borders 25h/module) -- logging is not at module granularity yet. Effort stays archetype-level until the new per-task tracking accumulates."
    },
    "backtest": {
      "median_ape_pct": 47.3,
      "iqr_coverage_pct": 42.9,
      "reading": "wide APE is expected -- it is the honest spread of a point guess; this is WHY the estimator must quote P25-P80 ranges, not points."
    }
  };
  // === END CALIBRATION =======================================================

  // --- ODL per-1-video rates (hours), from ODL Project Estimations ----------
  // pre = pre-production (scripting/prep), prod = filming, post = editing
  var videoRates = {
    studio_lecture:     { label: "Studio lecture video",   pre: 4,  prod: 0.5, post: 4 },
    lightboard:         { label: "Lightboard video",       pre: 4,  prod: 0.5, post: 4 },
    screencast:         { label: "Screencast (3–5 min)",   pre: 1,  prod: 0.5, post: 3 },
    testimonial:        { label: "Interview / testimonial",pre: 3,  prod: 1,   post: 30 },
    location_lecture:   { label: "On-location lecture",    pre: 8,  prod: 3,   post: 4 },
    location_interview: { label: "On-location interview",  pre: 7,  prod: 4,   post: 30 },
    minidoc:            { label: "Mini-documentary",       pre: 10, prod: 40,  post: 40 }
  };

  // --- Graphics / animation rates (hours), land in Post-Production & Build ---
  var graphicsRates = {
    explainer_animation: { label: "Explainer animation (3 min)", hours: 100 },
    animation_reuse:     { label: "Animation (reusing assets)",  hours: 43 },
    title_cards:         { label: "Title cards & lower thirds",  hours: 30 },
    infographic:         { label: "Infographic",                 hours: 4 },
    logo:                { label: "Logo / brand mark",           hours: 20 }
  };

  // --- XR / interactive rates (hours) ---------------------------------------
  var xrRates = {
    xr_linear:    { label: "Linear XR / 360 experience",    hours: 40 },
    xr_multipath: { label: "Branching XR / 360 experience", hours: 80 },
    unity:        { label: "Unity interactive (est.)",      hours: 80 }
  };

  // --- size-driven base hours for non-media phases (ODL planning estimates) --
  var courseMapHours    = { S: 8,  M: 16, L: 28, XL: 40 };
  var discoveryHours    = { S: 6,  M: 8,  L: 10, XL: 14 };
  var facDiscoveryHours = { S: 2,  M: 3,  L: 4,  XL: 6 };
  var facQAHours        = { S: 2,  M: 3,  L: 4,  XL: 5 };

  // --- Project-management effort across the whole project (CALIBRATED) ------
  // PM is logged ONLY on boards with a dedicated "PM Time Tracking" section
  // (10 boards, 679 h) — so a flat %-of-effort PM model would be an artifact.
  // Calibrated model: PM scales with calendar length. From the 14 PM-tracked
  // projects with reliable spans: 0.6–1.6 h/week (P25–P75), median 0.8,
  // P80 2.0, observed max 3.9 (flagship "AI for ND", 162 h over 42 wk).
  // pm = [weeks_lo × P25, weeks_hi × P75]; legacy buckets kept ONLY as a
  // fallback if the CALIBRATION block is missing.
  var pmHoursLegacy = { S: [5, 15], M: [15, 50], L: [75, 180], XL: [150, 300] };
  function pmFromWeeks(weeksLoHi, size) {
    var c = CALIBRATION && CALIBRATION.pmPerWeek;
    if (!c) { return pmHoursLegacy[size] || pmHoursLegacy.M; }
    return [Math.round(weeksLoHi[0] * c.p25), Math.round(weeksLoHi[1] * c.p75)];
  }

  // --- estimator types → historical archetypes (for CALIBRATION lookups) ----
  // null = no honest mapping in the logged data yet (do not force one).
  var TYPE_TO_ARCHETYPE = {
    new_course: "full_course", bisynchronous: "full_course",
    flipped: "full_course", ai: "full_course",
    xr: "xr_interactive", module: null
  };

  // --- calendar weeks per phase (base = Medium project ≈ 13 wk; scaled) ------
  var baseWeeksM = { discovery: 2, design: 3, preprod: 2, production: 2, postprod: 3, qa: 1, evaluation: 0 };
  var sizeWeekFactor = { S: 0.6, M: 1, L: 1.8, XL: 3 };

  // --- canonical phases + faculty-facing content ----------------------------
  var PHASES = [
    {
      key: "discovery", title: "Intake & Discovery", icon: "💬",
      whatHappens: "We review your idea, evaluate scope and feasibility, and align on pedagogical goals. You submit an intake form and meet the ODL team.",
      odlDoes: "Reviews intake, assesses feasibility, drafts the Project Charter and IP agreement.",
      youDo: "Share your vision, your learners, and the outcomes you want. Help us understand the context so we can scope accurately.",
      artifacts: ["Intake Form", "Draft Project Charter"]
    },
    {
      key: "design", title: "Design — Course Map", icon: "✏️",
      whatHappens: "We establish course and learning objectives, decide on content, and finalize the Course Map — the blueprint for the whole project.",
      odlDoes: "Leads design conversations, builds the Course Map, plans assessments and the media asset list.",
      youDo: "Act as the Subject-Matter Expert: lead the learning objectives and content mapping. This is your heaviest design-thinking phase.",
      artifacts: ["Course Map", "Design Document", "Media Asset List"]
    },
    {
      key: "preprod", title: "Pre-Production — Scripting", icon: "📝",
      whatHappens: "With the Course Map set, scripting begins (Draft → Review → Revise → Finalize), plus filming logistics, locations, and consent forms.",
      odlDoes: "Guides scripting sessions, builds the production schedule, secures locations, finalizes branding.",
      youDo: "Draft and review scripts for your videos. Time invested here makes filming smooth — it's the highest-leverage faculty work.",
      artifacts: ["Finalized Scripts", "Production Schedule", "Media Consent Form"]
    },
    {
      key: "production", title: "Production — Filming", icon: "🎬",
      whatHappens: "Lights, camera, action. Studio filming, on-location shoots, and B-roll capture of your core media.",
      odlDoes: "Runs the shoot — direction, lighting, audio, camera — and keeps you prepared and comfortable on camera.",
      youDo: "You're the on-camera talent. Attend filming sessions, deliver your content clearly, ensure technical accuracy.",
      artifacts: ["Raw Footage"]
    },
    {
      key: "postprod", title: "Post-Production & Build", icon: "🧩",
      whatHappens: "We edit footage, create graphics/animation, and build the course in Canvas (Rough Cut 1 → Rough Cut 2 → Final Cut).",
      odlDoes: "Edits all media, produces graphics/animations, and assembles the course site and assessments in the LMS.",
      youDo: "Review draft videos and course pages for accuracy and pedagogy. Build out supplementary materials (quizzes, assignments).",
      artifacts: ["Edited Videos", "Graphics", "Course Site (Canvas)"]
    },
    {
      key: "qa", title: "QA & Launch", icon: "🚀",
      whatHappens: "Rigorous quality assurance — accessibility (WCAG), content proofing — then the course goes live for students.",
      odlDoes: "Runs accessibility and QA checks, fixes issues, and launches the course on the LMS.",
      youDo: "Do a full walkthrough and give final approval to go live.",
      artifacts: ["Live Course", "QA Sign-off"]
    },
    {
      key: "evaluation", title: "Evaluation & Iteration", icon: "📊",
      whatHappens: "After launch we gather feedback, analyze performance data, and update the <a href=\"https://app.asana.com/1/228221773618853/project/1211592424221769\" target=\"_blank\" rel=\"noopener\">Asana Impact Tracker ↗</a> to understand the student experience and plan improvements.",
      odlDoes: "Sends the reflection survey, updates the impact tracker status, builds the report, and runs the retrospective.",
      youDo: "Review feedback and metrics with us; reflect and plan future enhancements.",
      artifacts: ["Evaluation Report", "<a href=\"https://app.asana.com/1/228221773618853/project/1211592424221769\" target=\"_blank\" rel=\"noopener\">Impact Tracker update ↗</a>"], ongoing: true
    }
  ];

  var PROJECT_TYPES = [
    { id: "new_course",    label: "New Course Creation",  desc: "A full online or hybrid course built from scratch — modules, videos, and assessments together.", ex: "e.g., a 6-module online course like “The Qur’an and the Bible.”", pick: "Pick this if you're building a whole course that doesn't exist yet." },
    { id: "bisynchronous", label: "Bisynchronous Course", desc: "A blend of live (synchronous) sessions and self-paced (asynchronous) online content.", ex: "e.g., leadership training run live across time zones, like MSAN II.", pick: "Pick this if learners meet live AND work through online material on their own." },
    { id: "flipped",       label: "Flipped Classroom",    desc: "Move lectures online so class time is freed up for active, hands-on learning.", ex: "e.g., pre-lab videos students watch before coming to the lab.", pick: "Pick this if you already teach in person and want to move content online." },
    { id: "ai",            label: "AI Training / Tool",   desc: "Build AI literacy into a course, or create an AI-powered tool for teaching and learning.", ex: "e.g., a campus-wide AI literacy course, or a Socratic AI tutor.", pick: "Pick this if AI is the subject, or you want an AI-powered learning tool." },
    { id: "xr",            label: "XR / Immersive",       desc: "Virtual or augmented reality, 360° video, or interactive simulations students step inside.", ex: "e.g., a VR Korean cultural immersion or a Spanish escape room.", pick: "Pick this if students will explore a simulated or 360° environment." },
    { id: "module",        label: "Single Module",        desc: "One focused digital learning unit, resource, or short video series — not a whole course.", ex: "e.g., a single high-impact module on digital accessibility.", pick: "Pick this if you need one focused piece, not a full course." }
  ];

  var PROJECT_SIZES = [
    { id: "S",  label: "Small",       desc: "One small piece — a few weeks of work.",  scope: "≈ 1–3 videos · 1–3 modules" },
    { id: "M",  label: "Medium",      desc: "A big chunk of a course — a few months.", scope: "≈ 8–10 videos · ~6 modules" },
    { id: "L",  label: "Large",       desc: "A complete course — a semester or more.", scope: "≈ 12–15 videos · ~10 modules" },
    { id: "XL", label: "Extra Large", desc: "A multi-course program — about a year.",   scope: "≈ 20+ videos · 16+ modules" }
  ];

  // --- typical deliverable bundles per type × size (counts) ------------------
  var BUNDLES = {
    new_course: {
      S:  { studio_lecture: 3, infographic: 1, modules: 3 },
      M:  { studio_lecture: 8, screencast: 2, animation_reuse: 1, infographic: 3, modules: 6 },
      L:  { studio_lecture: 12, testimonial: 1, explainer_animation: 1, infographic: 5, modules: 10 },
      XL: { studio_lecture: 20, testimonial: 2, explainer_animation: 2, infographic: 8, modules: 16 }
    },
    bisynchronous: {
      S:  { studio_lecture: 3, infographic: 1, modules: 3 },
      M:  { studio_lecture: 8, testimonial: 1, infographic: 3, modules: 6 },
      L:  { studio_lecture: 12, testimonial: 2, explainer_animation: 1, infographic: 5, modules: 10 },
      XL: { studio_lecture: 18, testimonial: 3, explainer_animation: 2, infographic: 8, modules: 16 }
    },
    flipped: {
      S:  { screencast: 4, modules: 2 },
      M:  { screencast: 8, studio_lecture: 2, infographic: 2, modules: 4 },
      L:  { screencast: 12, studio_lecture: 4, infographic: 3, modules: 8 },
      XL: { screencast: 20, studio_lecture: 6, animation_reuse: 1, modules: 12 }
    },
    ai: {
      S:  { screencast: 1, modules: 2 },
      M:  { screencast: 2, infographic: 1, modules: 4 },
      L:  { studio_lecture: 3, infographic: 2, modules: 6 },
      XL: { studio_lecture: 5, animation_reuse: 1, infographic: 2, modules: 10 }
    },
    xr: {
      S:  { xr_linear: 1, modules: 1 },
      M:  { xr_linear: 1, studio_lecture: 2, modules: 3 },
      L:  { xr_multipath: 1, xr_linear: 1, studio_lecture: 3, modules: 5 },
      XL: { xr_multipath: 2, xr_linear: 2, studio_lecture: 4, modules: 8 }
    },
    module: {
      S:  { screencast: 1, infographic: 1, modules: 1 },
      M:  { studio_lecture: 2, infographic: 1, modules: 1 },
      L:  { studio_lecture: 3, animation_reuse: 1, infographic: 2, modules: 2 },
      XL: { studio_lecture: 5, explainer_animation: 1, infographic: 3, modules: 3 }
    }
  };

  // --- a few real ND showcase projects for "similar projects" ---------------
  // `gid` = the Asana project GID (from data_all/projects.csv, matched on
  // normalized name), used to deep-link "View project in Asana". Entries with
  // no confident single match omit gid (ACE ASCENT is split across Phase II/III;
  // "AI Tutor" has no Asana board yet) and simply show no Asana link.
  var SHOWCASE = [
    { title: "The Qur’an and the Bible (Coursera)", gid: "1208255134984932", type: "new_course", size: "M", need: "A 6-module MOOC for a global audience.", link: "https://think.nd.edu/big_questions/new-on-coursera-sacred-texts-in-dialogue/" },
    { title: "AI for the ND Community", gid: "1209298164735103", type: "ai", size: "L", need: "Campus-wide AI literacy, modular by role.", link: "https://learning.nd.edu/news/announcing-ai-for-the-nd-community-course/" },
    { title: "ACE ASCENT", type: "new_course", size: "XL", need: "A multi-course teacher PD sequence for national cohorts.", link: "https://ace.nd.edu/ascent-research" },
    { title: "ACE Assessment Course Redesign", gid: "1208622917750063", type: "bisynchronous", size: "M", need: "Modernize an assessment course; blend workshops + online modules." },
    { title: "MSAN II", gid: "1208335647365608", type: "bisynchronous", size: "L", need: "Leadership training for military spouses across time zones.", link: "https://learning.nd.edu/news/notre-dames-partnership-with-military-spouse-advocacy-network-launches-second-course/" },
    { title: "Lab Visualization", gid: "1210202036254627", type: "flipped", size: "M", need: "Pre-lab videos to boost student readiness and safety.", link: "https://learning.nd.edu/news/visualizing-success-using-video-to-boost-student-lab-readiness-and-confidence/" },
    { title: "AI Tutor — Critical Thinking", type: "ai", size: "S", need: "A Socratic-style AI feedback tool." },
    { title: "Bringing Korean to Life", gid: "1210225716846542", type: "xr", size: "M", need: "VR/360 immersion + AI conversation avatars.", link: "https://www.library.nd.edu/news/korean-language-students-use-virtual-reality-to-explore-traditions/" },
    { title: "XR for Law — Car Crash", gid: "1209243150458283", type: "xr", size: "S", need: "A VR crash to study eyewitness fallibility.", link: "https://xr.nd.edu/projects/law-school-car-crash-simulator/" },
    { title: "Spanish Escape Room", gid: "1207760971753765", type: "xr", size: "L", need: "Gamified, collaborative Spanish language & culture.", link: "https://learning.nd.edu/news/ai-and-game-based-learning-enhance-study-of-spanish-language-and-culture/" },
    { title: "Digital Accessibility — Whitney James", gid: "1210225716846536", type: "module", size: "S", need: "A high-impact module on universal design / A11y." },
    { title: "AI Video Series", gid: "1207728646024488", type: "module", size: "M", need: "Fast-turnaround video series on generative AI.", link: "https://learning.nd.edu/learning-technology/lab-for-ai-in-teaching-and-learning-laitl/ai-for-teaching-and-learning-video-series/" }
  ];

  // ---------------------------------------------------------------------------
  // PURE COMPUTE
  // ---------------------------------------------------------------------------
  function round1(x) { return Math.round(x * 10) / 10; }
  function band(h, lo, hi) { return [Math.round(h * lo), Math.round(h * hi)]; }

  function bundleMediaHours(b) {
    var pre = 0, prod = 0, post = 0, graphics = 0, xr = 0;
    var videoCount = 0, graphicsCount = 0, xrCount = 0;
    for (var k in videoRates) {
      var n = b[k] || 0; videoCount += n;
      pre += n * videoRates[k].pre; prod += n * videoRates[k].prod; post += n * videoRates[k].post;
    }
    for (var g in graphicsRates) {
      var gn = b[g] || 0; graphicsCount += gn; graphics += gn * graphicsRates[g].hours;
    }
    for (var x in xrRates) {
      var xn = b[x] || 0; xrCount += xn; xr += xn * xrRates[x].hours;
    }
    return { pre: pre, prod: prod, post: post, graphics: graphics, xr: xr,
             videoCount: videoCount, modules: b.modules || 0,
             graphicsCount: graphicsCount, xrCount: xrCount,
             assetCount: videoCount + (b.modules || 0) + graphicsCount + xrCount };
  }

  function impactAssetEstimate(assetCount, pm) {
    var blk = CALIBRATION && CALIBRATION.impactCustomFields;
    var model = blk && blk.asset_hours_per_asset;
    var q = model && model.hours_per_asset;
    if (!model || !model.usable_for_estimation || !q || q.p25 == null || q.p75 == null || !assetCount) {
      return null;
    }
    var nonPm = [Math.round(assetCount * q.p25), Math.round(assetCount * q.p75)];
    return {
      assetCount: assetCount,
      nonPm: nonPm,
      totalWithPm: [nonPm[0] + pm[0], nonPm[1] + pm[1]],
      hoursPerAsset: q,
      basis: model.basis,
      matchedProjects: (model.matched_full_coverage_projects || []).length
    };
  }

  /* Estimate per phase from an explicit deliverable bundle.
     Returns { phases:[{key,title,icon,weeks:[lo,hi],odl:[lo,hi],faculty:[lo,hi]}],
               totals, media, bundle } */
  function estimateFromBundle(bundle, size) {
    size = size || "M";
    var m = bundleMediaHours(bundle);
    var wf = sizeWeekFactor[size] || 1;

    var odlH = {
      discovery: discoveryHours[size] || 8,
      design: (courseMapHours[size] || 16) + 2 + m.modules * 2,
      preprod: m.pre + m.modules * 0.5,
      production: m.prod,
      postprod: m.post + m.graphics + m.xr + m.modules * 2,
      qa: 5 + m.modules * 0.5,
      evaluation: 5
    };
    // --- FACULTY hands-on time per phase, as honest [lo,hi] ranges -----------
    // From ODL's learning-design & media leads' own estimates (2026):
    //   • media per video: 1h script (pre) + 1h film (prod) + 0.5h review (post)
    //   • design goals 2–4h (fixed) + course map scaled by size (~6–30h)
    //   • build/QA: 3–10h per module
    //   • meetings: ~1h per calendar week working with us (added to total below)
    // Planning estimates (no faculty time is logged yet) — shown as ranges.
    var V = m.videoCount, MOD = m.modules;
    // A single standalone module/resource isn't a course to map (MOD<=1): it gets
    // a lighter goals + short-outline pass. A multi-module course gets goals (2–4h,
    // fixed) plus a course map whose hours scale with the size of the course.
    var hasCourse = MOD >= 2;
    var courseMapHrs = { S: [6, 9], M: [10, 15], L: [16, 22], XL: [22, 30] }[size] || [10, 15];
    function pair(v) { return [Math.round(v * 0.8), Math.round(v * 1.3)]; }
    var facRange = {
      discovery:  pair(facDiscoveryHours[size] || 3),               // planning estimate (size-scaled)
      design:     hasCourse ? [2 + courseMapHrs[0], 4 + courseMapHrs[1]] : [2 + 2, 4 + 4], // goals 2–4 + (size-scaled course map | short outline 2–4)
      preprod:    [V * 1, V * 1],                                   // 1 h/video — script writing
      production: [V * 1, V * 1],                                   // 1 h/video — filming
      postprod:   [round1(V * 0.5) + MOD * 3, round1(V * 0.5) + MOD * 10], // 0.5 h/video review + 3–10 h/module build & QA
      qa:         [1, 3],                                           // final walkthrough & go-live sign-off
      evaluation: [2, 2]                                            // reviewing feedback after launch
    };

    // plain-language basis for each phase's faculty hours, so the (now larger)
    // numbers are self-explanatory where faculty actually see them
    function eachOf(n, noun) { return n === 1 ? ("your " + noun) : ("each of your " + n + " " + noun + "s"); }
    var postParts = [];
    if (V > 0) { postParts.push("about 30 min reviewing " + eachOf(V, "video")); }
    if (MOD > 0) { postParts.push("3–10 h helping build & check " + eachOf(MOD, "module")); }
    var facNote = {
      discovery:  "Sharing your vision, learners, and goals so we can scope it well.",
      design:     hasCourse
                    ? "About 2–4 h setting your learning goals, plus a " + courseMapHrs[0] + "–" + courseMapHrs[1] + " h course map (it grows with the size of the course) — the blueprint we build together."
                    : "About 2–4 h setting your learning goals and a short content outline (a single module doesn't need a full course map).",
      preprod:    V > 0 ? "About 1 h writing the script for " + eachOf(V, "video") + "." : "Scripting any narration or on-screen text.",
      production: V > 0 ? "About 1 h on camera filming " + eachOf(V, "video") + "." : "Any on-camera or recording time.",
      postprod:   postParts.length ? (postParts.join(", and ") + ".") : "Reviewing drafts for accuracy.",
      qa:         "A final walkthrough and your sign-off to go live.",
      evaluation: "Reviewing student feedback and results with us after launch."
    };

    var phases = PHASES.map(function (p) {
      var w = (baseWeeksM[p.key] || 0) * wf;
      var weeks = p.ongoing ? null : [Math.max(1, Math.round(w * 0.8)), Math.max(1, Math.round(w * 1.3))];
      var fr = facRange[p.key] || [0, 0];
      return {
        key: p.key, title: p.title, icon: p.icon,
        whatHappens: p.whatHappens, odlDoes: p.odlDoes, youDo: p.youDo,
        artifacts: p.artifacts, ongoing: !!p.ongoing,
        weeks: weeks,
        odl: band(odlH[p.key], 0.8, 1.25),
        faculty: [Math.round(fr[0]), Math.round(fr[1])],
        facNote: facNote[p.key] || ""
      };
    });

    var totOdl = [0, 0], totFac = [0, 0], totWk = [0, 0];
    phases.forEach(function (p) {
      totOdl[0] += p.odl[0]; totOdl[1] += p.odl[1];
      totFac[0] += p.faculty[0]; totFac[1] += p.faculty[1];
      if (p.weeks) { totWk[0] += p.weeks[0]; totWk[1] += p.weeks[1]; }
    });
    // project management runs across all phases; calibrated from ODL's own
    // PM time-tracking data (h per calendar week × the estimated timeline) —
    // added to the ODL-effort total as a line item
    var pm = pmFromWeeks(totWk, size);
    totOdl[0] += pm[0]; totOdl[1] += pm[1];
    // faculty meetings: ~1 h of working/meeting time per calendar week with ODL,
    // added to the faculty total as a line item (mirrors PM on the ODL side)
    var meetings = [Math.round(totWk[0] * 1), Math.round(totWk[1] * 1)];
    totFac[0] += meetings[0]; totFac[1] += meetings[1];
    var impactAsset = impactAssetEstimate(m.assetCount, pm);

    return {
      phases: phases,
      pm: pm,
      meetings: meetings,
      totals: { odl: totOdl, faculty: totFac, weeks: totWk },
      media: m, bundle: bundle, size: size,
      impactAsset: impactAsset
    };
  }

  /* What did SIMILAR REAL ODL PROJECTS actually take? Pure lookup into the
     CALIBRATION block (logged staff hours + completed_at calendar spans).
     Returns null when the type has no honest archetype mapping or no data:
     { archetype, n, productionHours:{p25,p50,p75,p80,...}, pmPerWeek,
       calendarWeeks, phaseMixPct, basis } — quartiles of real projects,
       independent of the bundle math above. */
  function estimateFromHistory(type) {
    if (!CALIBRATION) { return null; }
    var a = TYPE_TO_ARCHETYPE[type] || null;
    if (!a) { return null; }
    var eff = CALIBRATION.archetypeEffort[a] || null;
    var cal = CALIBRATION.calendarWeeks[a] || null;
    if (!eff && !cal) { return null; }
    return {
      archetype: a,
      productionHours: eff,                       // non-PM staff hours, quartiles
      pmPerWeek: CALIBRATION.pmPerWeek,           // multiply by calendar weeks
      calendarWeeks: cal,                         // real span quartiles
      phaseMixPct: a === "full_course" ? CALIBRATION.coursePhaseMixPct : null,
      basis: CALIBRATION.provenance
    };
  }

  function estimate(type, size) {
    var b = (BUNDLES[type] && BUNDLES[type][size]) || BUNDLES.module.S;
    var r = estimateFromBundle(b, size);
    r.type = type;
    r.history = estimateFromHistory(type);
    return r;
  }

  // Logged staff hours for a showcase project, matched by name to the hours
  // cross-check rows in CALIBRATION (real Asana time entries). null if no match.
  function loggedHoursForTitle(title) {
    var cf = CALIBRATION && CALIBRATION.impactCustomFields;
    var rows = cf && cf.hours_crosscheck && cf.hours_crosscheck.rows;
    if (!rows || !title) { return null; }
    var norm = String(title).toLowerCase().replace(/[^a-z0-9]+/g, " ").trim();
    for (var i = 0; i < rows.length; i++) {
      var rn = String(rows[i].project || "").toLowerCase().replace(/[^a-z0-9]+/g, " ").trim();
      if (rn && rn === norm) { return rows[i].asana_logged_hours; }
    }
    return null;
  }
  function sizeLabel(id) {
    var s = PROJECT_SIZES.filter(function (x) { return x.id === id; })[0];
    return s ? s.label : id;
  }

  /* Similar real ND projects of the same TYPE — exact size first, then other
     sizes. Each carries the effort a project that size tends to take (computed
     by the same engine) plus any real logged staff hours, so faculty can see
     how a project like theirs has actually played out — including ones that
     match their type but not their size. */
  function similarProjects(type, size) {
    var exact = SHOWCASE.filter(function (p) { return p.type === type && p.size === size; });
    var byType = SHOWCASE.filter(function (p) { return p.type === type && p.size !== size; });
    var list = exact.concat(byType).slice(0, 3);
    return list.map(function (p) {
      var est = estimate(p.type, p.size);
      return {
        title: p.title, need: p.need, link: p.link, gid: p.gid,
        type: p.type, size: p.size,
        sizeMatch: p.size === size,
        sizeLabel: sizeLabel(p.size),
        yourSizeLabel: sizeLabel(size),
        effort: { odl: est.totals.odl, faculty: est.totals.faculty, weeks: est.totals.weeks },
        loggedHours: loggedHoursForTitle(p.title)
      };
    });
  }

  function deliverableLabel(key) {
    if (videoRates[key]) return videoRates[key].label;
    if (graphicsRates[key]) return graphicsRates[key].label;
    if (xrRates[key]) return xrRates[key].label;
    if (key === "modules") return "Course modules";
    return key;
  }

  /* Infer a project's type + size BACKWARDS from a rough description
     ("about 8 modules and 10 videos") by nearest-neighbor against the
     project library profiles, then estimate hours from the USER'S counts.
     Deterministic — no AI invents anything.
     input: { modules, videos, style: 'lecture'|'screencast'|'mix',
              animations, infographics, xr: bool } */
  function inferProject(input) {
    var m = Math.max(0, input.modules || 0);
    var v = Math.max(0, input.videos || 0);
    var anim = Math.max(0, input.animations || 0);
    var info = Math.max(0, input.infographics || 0);
    var xr = input.xr ? 1 : 0;

    // the user's actual deliverable bundle (drives the hour computation)
    var bundle = { modules: m };
    if (input.style === "screencast") { bundle.screencast = v; }
    else if (input.style === "mix") {
      bundle.studio_lecture = Math.ceil(v / 2);
      bundle.screencast = Math.floor(v / 2);
    } else { bundle.studio_lecture = v; }
    if (anim) bundle.animation_reuse = anim;
    if (info) bundle.infographic = info;
    if (xr) bundle.xr_linear = 1;

    // nearest profile in the type x size library (drives size-based items:
    // PM hours, timeline weeks, discovery/course-map/QA bases)
    var best = null;
    for (var t in BUNDLES) {
      for (var s in BUNDLES[t]) {
        var b = BUNDLES[t][s];
        var bv = 0;
        for (var k in videoRates) { bv += b[k] || 0; }
        var bm = b.modules || 0;
        var bg = (b.explainer_animation || 0) + (b.animation_reuse || 0) +
                 (b.infographic || 0) + (b.title_cards || 0);
        var bx = ((b.xr_linear || 0) + (b.xr_multipath || 0) + (b.unity || 0)) > 0 ? 1 : 0;
        var d = Math.pow((v - bv) / 4, 2) + Math.pow((m - bm) / 3, 2) +
                Math.pow(((anim + info) - bg) / 3, 2) + Math.pow((xr - bx) * 2, 2);
        if (!best || d < best.d) { best = { d: d, type: t, size: s }; }
      }
    }

    var est = estimateFromBundle(bundle, best.size);
    est.type = best.type;
    est.inferred = { type: best.type, size: best.size };
    return est;
  }

  var API = {
    PHASES: PHASES, PROJECT_TYPES: PROJECT_TYPES, PROJECT_SIZES: PROJECT_SIZES,
    BUNDLES: BUNDLES, SHOWCASE: SHOWCASE,
    videoRates: videoRates, graphicsRates: graphicsRates, xrRates: xrRates,
    CALIBRATION: CALIBRATION, TYPE_TO_ARCHETYPE: TYPE_TO_ARCHETYPE,
    estimate: estimate, estimateFromBundle: estimateFromBundle,
    estimateFromHistory: estimateFromHistory,
    inferProject: inferProject,
    similarProjects: similarProjects, deliverableLabel: deliverableLabel
  };

  root.ODL = API;
  if (typeof module !== "undefined" && module.exports) { module.exports = API; }
})(typeof window !== "undefined" ? window : this);
