/* =============================================================================
   ODL Interactive Process Guide — estimation engine + content data
   -----------------------------------------------------------------------------
   PROVENANCE OF NUMBERS (so every figure is defensible to faculty / the Director):
   - CALIBRATION block below is machine-generated by ../inject_calibration.py
     from data_all/derived/calibration.json — itself computed by ../calibrate.py
     from 2,335 real Asana time entries (2,053 h, 2024-08 → 2026-06, 55 projects;
     calibration set = 25 fully-tracked course-dev projects). Do NOT edit the
     block by hand; re-run the pipeline after each new Asana pull.
   - Media/graphics per-deliverable HOURS come from ODL's own "ODL Project
     Estimations" Asana board (Nov 2024), incl. Pre/Prod/Post splits. Logged
     data validates the lecture-band rates: observed full-lifecycle short-video
     median 12.8 h/video (n=5), shrinkage-blended generic rate 11.2 h/video.
     Interview/testimonial/mini-doc rates remain UNVALIDATED (no fully-logged
     exemplar yet).
   - PM hours are CALIBRATED: hours-per-calendar-week quartiles from the 14
     PM-tracked projects (replaces the old size-bucket extrapolation).
   - Calendar: per-archetype span quartiles from completed_at timestamps with
     bulk check-off filtering (full courses: median 31 wk, IQR 18–42, n=23).
   - Design / Discovery / QA / Evaluation hours and all FACULTY-time figures are
     ODL planning estimates (labeled as such) — logged data contains ZERO faculty
     time and <15 h each of Discovery/QA/Evaluation, so they cannot be calibrated
     yet (see calibration.json not_calibratable).
   Architecture: this file computes ALL numbers deterministically. No AI/LLM
   number generation. Estimates are ranges, never false-precision points.
   ============================================================================= */
(function (root) {
  "use strict";

  // === BEGIN CALIBRATION (machine-generated — do not edit by hand) ==========
  var CALIBRATION =
  {
    "provenance": "data_all/time_entries.csv (2,347 entries, 2069.0h, 2024-08-19..2026-06-08, ODL staff time) | 25 full-coverage course-dev projects >=10h (derived/ground_truth.csv); production rates from the 21 of them with >=10h non-PM logging",
    "generated_from": "data_all/derived/calibration.json -- run inject_calibration.py to refresh",
    "archetypeEffort": {
      "course_redesign": {
        "n": 2,
        "values": [
          32.3,
          33.4
        ],
        "p50": 32.8,
        "note": "n<4 -- raw values shown; interpolated quartiles withheld"
      },
      "full_course": {
        "n": 14,
        "min": 15.7,
        "p25": 21.5,
        "p50": 42.8,
        "p75": 65.6,
        "p80": 74.2,
        "max": 286.5
      },
      "single_video": {
        "n": 3,
        "values": [
          12.0,
          13.5,
          15.5
        ],
        "p50": 13.5,
        "note": "n<4 -- raw values shown; interpolated quartiles withheld"
      },
      "video_series": {
        "n": 2,
        "values": [
          29.2,
          54.8
        ],
        "p50": 42.0,
        "note": "n<4 -- raw values shown; interpolated quartiles withheld"
      }
    },
    "pmPerWeek": {
      "n": 14,
      "min": 0.3,
      "p25": 0.6,
      "p50": 0.8,
      "p75": 1.6,
      "p80": 2.0,
      "max": 3.9
    },
    "pmSharePctWhereBothLogged": {
      "n": 7,
      "min": 14.7,
      "p25": 18.9,
      "p50": 36.1,
      "p75": 51.0,
      "p80": 59.1,
      "max": 73.3
    },
    "videoRate": {
      "observed": {
        "n": 5,
        "min": 7.3,
        "p25": 12.0,
        "p50": 13.5,
        "p75": 13.7,
        "p80": 14.1,
        "max": 15.5
      },
      "blendedGenericP50": 11.6,
      "shrinkageW": 0.62
    },
    "mediaSplitPct": {
      "Post-Production": 41.9,
      "Pre-Production": 25.8,
      "Production": 32.3
    },
    "mediaSplitBasis": "pooled hours on per-video sections with full-coverage logging: 1 project(s) (Program for Inclusive Education (PIE) Video #2), 15.5h total",
    "coursePhaseMixPct": {
      "Production": 31.8,
      "Post-Production": 21.6,
      "Development/Build": 18.2,
      "Pre-Production": 18.0,
      "Design": 8.8,
      "Other / unsorted": 1.1,
      "Discovery": 0.5
    },
    "coursePhaseMixBasis": "pooled non-PM hours of 14 full-coverage full_course projects (855.5h)",
    "calendarWeeks": {
      "consult_or_studio": {
        "n": 1,
        "values": [
          44.0
        ]
      },
      "course_redesign": {
        "n": 3,
        "values": [
          7.8,
          10.3,
          23.3
        ],
        "p50": 10.3,
        "note": "n<4 -- raw values shown; interpolated quartiles withheld"
      },
      "full_course": {
        "n": 23,
        "min": 4.8,
        "p25": 17.7,
        "p50": 31.4,
        "p75": 41.9,
        "p80": 46.6,
        "max": 63.6
      },
      "podcast": {
        "n": 2,
        "values": [
          6.5,
          84.6
        ],
        "p50": 45.5,
        "note": "n<4 -- raw values shown; interpolated quartiles withheld"
      },
      "single_video": {
        "n": 4,
        "min": 2.0,
        "p25": 2.4,
        "p50": 3.9,
        "p75": 7.2,
        "p80": 8.4,
        "max": 13.0
      },
      "sprint": {
        "n": 1,
        "values": [
          13.9
        ]
      },
      "video_series": {
        "n": 4,
        "min": 5.4,
        "p25": 9.6,
        "p50": 12.1,
        "p75": 14.3,
        "p80": 14.9,
        "max": 17.4
      },
      "xr_interactive": {
        "n": 4,
        "min": 10.0,
        "p25": 10.8,
        "p50": 16.0,
        "p75": 22.0,
        "p80": 22.7,
        "max": 25.3
      }
    },
    "notCalibratable": {
      "faculty_time": "time_entries contains ODL STAFF time only -- zero faculty hours logged. All faculty-time figures remain planning estimates and must be labeled as such.",
      "discovery_effort": "only 11.0h logged across all projects -- discovery happens before boards get tracked. Insufficient.",
      "evaluation_effort": "only 1.0h logged total. Insufficient.",
      "qa_effort": "only 1.7h logged total. Insufficient.",
      "interview_minidoc_video_rates": "no full-coverage logged exemplar (see video block).",
      "xr_effort": "XR projects in data have <=6h logged (Equity XR 6h, XR Spanish 1h) -- board rates (40-80h) stand, unvalidated.",
      "per_module_rate": "module counts exist for only 5 of 19 course projects and mean different things (AI for ND 57h/module vs R&E AI 7.6h/week-unit vs Virtual Borders 25h/module) -- logging is not at module granularity yet. Effort stays archetype-level until the new per-task tracking accumulates."
    },
    "backtest": {
      "median_ape_pct": 55.8,
      "iqr_coverage_pct": 42.9,
      "reading": "wide APE is expected -- it is the honest spread of a point guess; this is WHY the estimator must quote P25-P80 ranges, not points."
    }
  };
  // === END CALIBRATION =======================================================

  // --- ODL per-1-video rates (hours), from ODL Project Estimations ----------
  // pre = pre-production (scripting/prep), prod = filming, post = editing
  var videoRates = {
    studio_lecture:     { label: "Studio lecture video",   pre: 4,  prod: 0.5, post: 4 },
    lightboard:         { label: "Lightboard video",       pre: 4,  prod: 0.5, post: 4 },
    screencast:         { label: "Screencast (3–5 min)",   pre: 1,  prod: 0.5, post: 3 },
    testimonial:        { label: "Interview / testimonial",pre: 3,  prod: 1,   post: 30 },
    location_lecture:   { label: "On-location lecture",    pre: 8,  prod: 3,   post: 4 },
    location_interview: { label: "On-location interview",  pre: 7,  prod: 4,   post: 30 },
    minidoc:            { label: "Mini-documentary",       pre: 10, prod: 40,  post: 40 }
  };

  // --- Graphics / animation rates (hours), land in Post-Production & Build ---
  var graphicsRates = {
    explainer_animation: { label: "Explainer animation (3 min)", hours: 100 },
    animation_reuse:     { label: "Animation (reusing assets)",  hours: 43 },
    title_cards:         { label: "Title cards & lower thirds",  hours: 30 },
    infographic:         { label: "Infographic",                 hours: 4 },
    logo:                { label: "Logo / brand mark",           hours: 20 }
  };

  // --- XR / interactive rates (hours) ---------------------------------------
  var xrRates = {
    xr_linear:    { label: "Linear XR / 360 experience",    hours: 40 },
    xr_multipath: { label: "Branching XR / 360 experience", hours: 80 },
    unity:        { label: "Unity interactive (est.)",      hours: 80 }
  };

  // --- size-driven base hours for non-media phases (ODL planning estimates) --
  var courseMapHours    = { S: 8,  M: 16, L: 28, XL: 40 };
  var discoveryHours    = { S: 6,  M: 8,  L: 10, XL: 14 };
  var facDiscoveryHours = { S: 2,  M: 3,  L: 4,  XL: 6 };
  var facQAHours        = { S: 2,  M: 3,  L: 4,  XL: 5 };

  // --- Project-management effort across the whole project (CALIBRATED) ------
  // PM is logged ONLY on boards with a dedicated "PM Time Tracking" section
  // (10 boards, 679 h) — so a flat %-of-effort PM model would be an artifact.
  // Calibrated model: PM scales with calendar length. From the 14 PM-tracked
  // projects with reliable spans: 0.6–1.6 h/week (P25–P75), median 0.8,
  // P80 2.0, observed max 3.9 (flagship "AI for ND", 162 h over 42 wk).
  // pm = [weeks_lo × P25, weeks_hi × P75]; legacy buckets kept ONLY as a
  // fallback if the CALIBRATION block is missing.
  var pmHoursLegacy = { S: [5, 15], M: [15, 50], L: [75, 180], XL: [150, 300] };
  function pmFromWeeks(weeksLoHi, size) {
    var c = CALIBRATION && CALIBRATION.pmPerWeek;
    if (!c) { return pmHoursLegacy[size] || pmHoursLegacy.M; }
    return [Math.round(weeksLoHi[0] * c.p25), Math.round(weeksLoHi[1] * c.p75)];
  }

  // --- estimator types → historical archetypes (for CALIBRATION lookups) ----
  // null = no honest mapping in the logged data yet (do not force one).
  var TYPE_TO_ARCHETYPE = {
    new_course: "full_course", bisynchronous: "full_course",
    flipped: "full_course", ai: "full_course",
    xr: "xr_interactive", module: null
  };

  // --- calendar weeks per phase (base = Medium project ≈ 13 wk; scaled) ------
  var baseWeeksM = { discovery: 2, design: 3, preprod: 2, production: 2, postprod: 3, qa: 1, evaluation: 0 };
  var sizeWeekFactor = { S: 0.6, M: 1, L: 1.8, XL: 3 };

  // --- canonical phases + faculty-facing content ----------------------------
  var PHASES = [
    {
      key: "discovery", title: "Intake & Discovery", icon: "💬",
      whatHappens: "We review your idea, evaluate scope and feasibility, and align on pedagogical goals. You submit an intake form and meet the ODL team.",
      odlDoes: "Reviews intake, assesses feasibility, drafts the Project Charter and IP agreement.",
      youDo: "Share your vision, your learners, and the outcomes you want. Help us understand the context so we can scope accurately.",
      artifacts: ["Intake Form", "Draft Project Charter"]
    },
    {
      key: "design", title: "Design — Course Map", icon: "✏️",
      whatHappens: "We establish course and learning objectives, decide on content, and finalize the Course Map — the blueprint for the whole project.",
      odlDoes: "Leads design conversations, builds the Course Map, plans assessments and the media asset list.",
      youDo: "Act as the Subject-Matter Expert: lead the learning objectives and content mapping. This is your heaviest design-thinking phase.",
      artifacts: ["Course Map", "Design Document", "Media Asset List"]
    },
    {
      key: "preprod", title: "Pre-Production — Scripting", icon: "📝",
      whatHappens: "With the Course Map set, scripting begins (Draft → Review → Revise → Finalize), plus filming logistics, locations, and consent forms.",
      odlDoes: "Guides scripting sessions, builds the production schedule, secures locations, finalizes branding.",
      youDo: "Draft and review scripts for your videos. Time invested here makes filming smooth — it's the highest-leverage faculty work.",
      artifacts: ["Finalized Scripts", "Production Schedule", "Media Consent Form"]
    },
    {
      key: "production", title: "Production — Filming", icon: "🎬",
      whatHappens: "Lights, camera, action. Studio filming, on-location shoots, and B-roll capture of your core media.",
      odlDoes: "Runs the shoot — direction, lighting, audio, camera — and keeps you prepared and comfortable on camera.",
      youDo: "You're the on-camera talent. Attend filming sessions, deliver your content clearly, ensure technical accuracy.",
      artifacts: ["Raw Footage"]
    },
    {
      key: "postprod", title: "Post-Production & Build", icon: "🧩",
      whatHappens: "We edit footage, create graphics/animation, and build the course in Canvas (Rough Cut 1 → Rough Cut 2 → Final Cut).",
      odlDoes: "Edits all media, produces graphics/animations, and assembles the course site and assessments in the LMS.",
      youDo: "Review draft videos and course pages for accuracy and pedagogy. Build out supplementary materials (quizzes, assignments).",
      artifacts: ["Edited Videos", "Graphics", "Course Site (Canvas)"]
    },
    {
      key: "qa", title: "QA & Launch", icon: "🚀",
      whatHappens: "Rigorous quality assurance — accessibility (WCAG), content proofing — then the course goes live for students.",
      odlDoes: "Runs accessibility and QA checks, fixes issues, and launches the course on the LMS.",
      youDo: "Do a full walkthrough and give final approval to go live.",
      artifacts: ["Live Course", "QA Sign-off"]
    },
    {
      key: "evaluation", title: "Evaluation & Iteration", icon: "📊",
      whatHappens: "After launch we gather feedback and performance data to understand the student experience and plan improvements.",
      odlDoes: "Sends the reflection survey, builds the report, runs the retrospective.",
      youDo: "Review feedback and metrics with us; reflect and plan future enhancements.",
      artifacts: ["Evaluation Report"], ongoing: true
    }
  ];

  var PROJECT_TYPES = [
    { id: "new_course",    label: "New Course Creation",  desc: "A full online or hybrid course built from scratch." },
    { id: "bisynchronous", label: "Bisynchronous Course", desc: "A blend of synchronous and asynchronous learning." },
    { id: "flipped",       label: "Flipped Classroom",    desc: "Move content online; active learning in class." },
    { id: "ai",            label: "AI Training / Tool",   desc: "Incorporate AI tools and literacy into the curriculum." },
    { id: "xr",            label: "XR / Immersive",       desc: "VR, AR, 360 video, or interactive simulations." },
    { id: "module",        label: "Single Module",        desc: "One focused digital learning unit or resource." }
  ];

  var PROJECT_SIZES = [
    { id: "S",  label: "Small",       desc: "A single module or short resource." },
    { id: "M",  label: "Medium",      desc: "A significant portion of a course." },
    { id: "L",  label: "Large",       desc: "A full course or complex experience." },
    { id: "XL", label: "Extra Large", desc: "A multi-course sequence or initiative." }
  ];

  // --- typical deliverable bundles per type × size (counts) ------------------
  var BUNDLES = {
    new_course: {
      S:  { studio_lecture: 3, infographic: 1, modules: 3 },
      M:  { studio_lecture: 8, screencast: 2, animation_reuse: 1, infographic: 3, modules: 6 },
      L:  { studio_lecture: 12, testimonial: 1, explainer_animation: 1, infographic: 5, modules: 10 },
      XL: { studio_lecture: 20, testimonial: 2, explainer_animation: 2, infographic: 8, modules: 16 }
    },
    bisynchronous: {
      S:  { studio_lecture: 3, infographic: 1, modules: 3 },
      M:  { studio_lecture: 8, testimonial: 1, infographic: 3, modules: 6 },
      L:  { studio_lecture: 12, testimonial: 2, explainer_animation: 1, infographic: 5, modules: 10 },
      XL: { studio_lecture: 18, testimonial: 3, explainer_animation: 2, infographic: 8, modules: 16 }
    },
    flipped: {
      S:  { screencast: 4, modules: 2 },
      M:  { screencast: 8, studio_lecture: 2, infographic: 2, modules: 4 },
      L:  { screencast: 12, studio_lecture: 4, infographic: 3, modules: 8 },
      XL: { screencast: 20, studio_lecture: 6, animation_reuse: 1, modules: 12 }
    },
    ai: {
      S:  { screencast: 1, modules: 2 },
      M:  { screencast: 2, infographic: 1, modules: 4 },
      L:  { studio_lecture: 3, infographic: 2, modules: 6 },
      XL: { studio_lecture: 5, animation_reuse: 1, infographic: 2, modules: 10 }
    },
    xr: {
      S:  { xr_linear: 1, modules: 1 },
      M:  { xr_linear: 1, studio_lecture: 2, modules: 3 },
      L:  { xr_multipath: 1, xr_linear: 1, studio_lecture: 3, modules: 5 },
      XL: { xr_multipath: 2, xr_linear: 2, studio_lecture: 4, modules: 8 }
    },
    module: {
      S:  { screencast: 1, infographic: 1, modules: 1 },
      M:  { studio_lecture: 2, infographic: 1, modules: 1 },
      L:  { studio_lecture: 3, animation_reuse: 1, infographic: 2, modules: 2 },
      XL: { studio_lecture: 5, explainer_animation: 1, infographic: 3, modules: 3 }
    }
  };

  // --- a few real ND showcase projects for "similar projects" ---------------
  var SHOWCASE = [
    { title: "The Qur’an and the Bible (Coursera)", type: "new_course", size: "M", need: "A 6-module MOOC for a global audience.", link: "https://think.nd.edu/big_questions/new-on-coursera-sacred-texts-in-dialogue/" },
    { title: "AI for the ND Community", type: "ai", size: "L", need: "Campus-wide AI literacy, modular by role.", link: "https://learning.nd.edu/news/announcing-ai-for-the-nd-community-course/" },
    { title: "ACE ASCENT", type: "new_course", size: "XL", need: "A multi-course teacher PD sequence for national cohorts.", link: "https://ace.nd.edu/ascent-research" },
    { title: "ACE Assessment Course Redesign", type: "bisynchronous", size: "M", need: "Modernize an assessment course; blend workshops + online modules.", link: "https://ace.nd.edu/" },
    { title: "MSAN II", type: "bisynchronous", size: "L", need: "Leadership training for military spouses across time zones.", link: "https://learning.nd.edu/news/notre-dames-partnership-with-military-spouse-advocacy-network-launches-second-course/" },
    { title: "Lab Visualization", type: "flipped", size: "M", need: "Pre-lab videos to boost student readiness and safety.", link: "https://learning.nd.edu/news/visualizing-success-using-video-to-boost-student-lab-readiness-and-confidence/" },
    { title: "AI Tutor — Critical Thinking", type: "ai", size: "S", need: "A Socratic-style AI feedback tool.", link: "https://learning.nd.edu/" },
    { title: "Bringing Korean to Life", type: "xr", size: "M", need: "VR/360 immersion + AI conversation avatars.", link: "https://www.library.nd.edu/news/korean-language-students-use-virtual-reality-to-explore-traditions/" },
    { title: "XR for Law — Car Crash", type: "xr", size: "S", need: "A VR crash to study eyewitness fallibility.", link: "https://xr.nd.edu/projects/law-school-car-crash-simulator/" },
    { title: "Spanish Escape Room", type: "xr", size: "L", need: "Gamified, collaborative Spanish language & culture.", link: "https://learning.nd.edu/news/ai-and-game-based-learning-enhance-study-of-spanish-language-and-culture/" },
    { title: "Digital Accessibility — Whitney James", type: "module", size: "S", need: "A high-impact module on universal design / A11y.", link: "https://accessibility.nd.edu/" },
    { title: "AI Video Series", type: "module", size: "M", need: "Fast-turnaround video series on generative AI.", link: "https://learning.nd.edu/learning-technology/lab-for-ai-in-teaching-and-learning-laitl/ai-for-teaching-and-learning-video-series/" }
  ];

  // ---------------------------------------------------------------------------
  // PURE COMPUTE
  // ---------------------------------------------------------------------------
  function round1(x) { return Math.round(x * 10) / 10; }
  function band(h, lo, hi) { return [Math.round(h * lo), Math.round(h * hi)]; }

  function bundleMediaHours(b) {
    var pre = 0, prod = 0, post = 0, graphics = 0, xr = 0, videoCount = 0;
    for (var k in videoRates) {
      var n = b[k] || 0; videoCount += n;
      pre += n * videoRates[k].pre; prod += n * videoRates[k].prod; post += n * videoRates[k].post;
    }
    for (var g in graphicsRates) { graphics += (b[g] || 0) * graphicsRates[g].hours; }
    for (var x in xrRates) { xr += (b[x] || 0) * xrRates[x].hours; }
    return { pre: pre, prod: prod, post: post, graphics: graphics, xr: xr,
             videoCount: videoCount, modules: b.modules || 0 };
  }

  /* Estimate per phase from an explicit deliverable bundle.
     Returns { phases:[{key,title,icon,weeks:[lo,hi],odl:[lo,hi],faculty:[lo,hi]}],
               totals, media, bundle } */
  function estimateFromBundle(bundle, size) {
    size = size || "M";
    var m = bundleMediaHours(bundle);
    var wf = sizeWeekFactor[size] || 1;

    var odlH = {
      discovery: discoveryHours[size] || 8,
      design: (courseMapHours[size] || 16) + 2 + m.modules * 2,
      preprod: m.pre + m.modules * 0.5,
      production: m.prod,
      postprod: m.post + m.graphics + m.xr + m.modules * 2,
      qa: 5 + m.modules * 0.5,
      evaluation: 5
    };
    var facH = {
      discovery: facDiscoveryHours[size] || 3,
      design: 3 + m.modules * 0.6,
      preprod: m.videoCount * 1.0,
      production: m.prod * 1.0,
      postprod: m.videoCount * 0.5,
      qa: facQAHours[size] || 3,
      evaluation: 2
    };

    var phases = PHASES.map(function (p) {
      var w = (baseWeeksM[p.key] || 0) * wf;
      var weeks = p.ongoing ? null : [Math.max(1, Math.round(w * 0.8)), Math.max(1, Math.round(w * 1.3))];
      return {
        key: p.key, title: p.title, icon: p.icon,
        whatHappens: p.whatHappens, odlDoes: p.odlDoes, youDo: p.youDo,
        artifacts: p.artifacts, ongoing: !!p.ongoing,
        weeks: weeks,
        odl: band(odlH[p.key], 0.8, 1.25),
        faculty: band(facH[p.key], 0.8, 1.3)
      };
    });

    var totOdl = [0, 0], totFac = [0, 0], totWk = [0, 0];
    phases.forEach(function (p) {
      totOdl[0] += p.odl[0]; totOdl[1] += p.odl[1];
      totFac[0] += p.faculty[0]; totFac[1] += p.faculty[1];
      if (p.weeks) { totWk[0] += p.weeks[0]; totWk[1] += p.weeks[1]; }
    });
    // project management runs across all phases; calibrated from ODL's own
    // PM time-tracking data (h per calendar week × the estimated timeline) —
    // added to the ODL-effort total as a line item
    var pm = pmFromWeeks(totWk, size);
    totOdl[0] += pm[0]; totOdl[1] += pm[1];

    return {
      phases: phases,
      pm: pm,
      totals: { odl: totOdl, faculty: totFac, weeks: totWk },
      media: m, bundle: bundle, size: size
    };
  }

  /* What did SIMILAR REAL ODL PROJECTS actually take? Pure lookup into the
     CALIBRATION block (logged staff hours + completed_at calendar spans).
     Returns null when the type has no honest archetype mapping or no data:
     { archetype, n, productionHours:{p25,p50,p75,p80,...}, pmPerWeek,
       calendarWeeks, phaseMixPct, basis } — quartiles of real projects,
       independent of the bundle math above. */
  function estimateFromHistory(type) {
    if (!CALIBRATION) { return null; }
    var a = TYPE_TO_ARCHETYPE[type] || null;
    if (!a) { return null; }
    var eff = CALIBRATION.archetypeEffort[a] || null;
    var cal = CALIBRATION.calendarWeeks[a] || null;
    if (!eff && !cal) { return null; }
    return {
      archetype: a,
      productionHours: eff,                       // non-PM staff hours, quartiles
      pmPerWeek: CALIBRATION.pmPerWeek,           // multiply by calendar weeks
      calendarWeeks: cal,                         // real span quartiles
      phaseMixPct: a === "full_course" ? CALIBRATION.coursePhaseMixPct : null,
      basis: CALIBRATION.provenance
    };
  }

  function estimate(type, size) {
    var b = (BUNDLES[type] && BUNDLES[type][size]) || BUNDLES.module.S;
    var r = estimateFromBundle(b, size);
    r.type = type;
    r.history = estimateFromHistory(type);
    return r;
  }

  function similarProjects(type, size) {
    var exact = SHOWCASE.filter(function (p) { return p.type === type && p.size === size; });
    var byType = SHOWCASE.filter(function (p) { return p.type === type && p.size !== size; });
    return exact.concat(byType).slice(0, 3);
  }

  function deliverableLabel(key) {
    if (videoRates[key]) return videoRates[key].label;
    if (graphicsRates[key]) return graphicsRates[key].label;
    if (xrRates[key]) return xrRates[key].label;
    if (key === "modules") return "Course modules";
    return key;
  }

  /* Infer a project's type + size BACKWARDS from a rough description
     ("about 8 modules and 10 videos") by nearest-neighbor against the
     project library profiles, then estimate hours from the USER'S counts.
     Deterministic — no AI invents anything.
     input: { modules, videos, style: 'lecture'|'screencast'|'mix',
              animations, infographics, xr: bool } */
  function inferProject(input) {
    var m = Math.max(0, input.modules || 0);
    var v = Math.max(0, input.videos || 0);
    var anim = Math.max(0, input.animations || 0);
    var info = Math.max(0, input.infographics || 0);
    var xr = input.xr ? 1 : 0;

    // the user's actual deliverable bundle (drives the hour computation)
    var bundle = { modules: m };
    if (input.style === "screencast") { bundle.screencast = v; }
    else if (input.style === "mix") {
      bundle.studio_lecture = Math.ceil(v / 2);
      bundle.screencast = Math.floor(v / 2);
    } else { bundle.studio_lecture = v; }
    if (anim) bundle.animation_reuse = anim;
    if (info) bundle.infographic = info;
    if (xr) bundle.xr_linear = 1;

    // nearest profile in the type x size library (drives size-based items:
    // PM hours, timeline weeks, discovery/course-map/QA bases)
    var best = null;
    for (var t in BUNDLES) {
      for (var s in BUNDLES[t]) {
        var b = BUNDLES[t][s];
        var bv = 0;
        for (var k in videoRates) { bv += b[k] || 0; }
        var bm = b.modules || 0;
        var bg = (b.explainer_animation || 0) + (b.animation_reuse || 0) +
                 (b.infographic || 0) + (b.title_cards || 0);
        var bx = ((b.xr_linear || 0) + (b.xr_multipath || 0) + (b.unity || 0)) > 0 ? 1 : 0;
        var d = Math.pow((v - bv) / 4, 2) + Math.pow((m - bm) / 3, 2) +
                Math.pow(((anim + info) - bg) / 3, 2) + Math.pow((xr - bx) * 2, 2);
        if (!best || d < best.d) { best = { d: d, type: t, size: s }; }
      }
    }

    var est = estimateFromBundle(bundle, best.size);
    est.type = best.type;
    est.inferred = { type: best.type, size: best.size };
    return est;
  }

  var API = {
    PHASES: PHASES, PROJECT_TYPES: PROJECT_TYPES, PROJECT_SIZES: PROJECT_SIZES,
    BUNDLES: BUNDLES, SHOWCASE: SHOWCASE,
    videoRates: videoRates, graphicsRates: graphicsRates, xrRates: xrRates,
    CALIBRATION: CALIBRATION, TYPE_TO_ARCHETYPE: TYPE_TO_ARCHETYPE,
    estimate: estimate, estimateFromBundle: estimateFromBundle,
    estimateFromHistory: estimateFromHistory,
    inferProject: inferProject,
    similarProjects: similarProjects, deliverableLabel: deliverableLabel
  };

  root.ODL = API;
  if (typeof module !== "undefined" && module.exports) { module.exports = API; }
})(typeof window !== "undefined" ? window : this);
